// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkjCVL13E4dURPQAHtj3zqXiI8sz6ZE1E',
    appId: '1:626097842743:web:963fd6dc32c55fbf5bedb2',
    messagingSenderId: '626097842743',
    projectId: 'smart-23dec',
    authDomain: 'smart-23dec.firebaseapp.com',
    storageBucket: 'smart-23dec.firebasestorage.app',
    measurementId: 'G-JLRH0S7SRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjRg2ZqBxm0YjgiuS7DvMvTKJFB3dF8Qg',
    appId: '1:626097842743:android:09ff772d9cbebbf05bedb2',
    messagingSenderId: '626097842743',
    projectId: 'smart-23dec',
    storageBucket: 'smart-23dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvnqspO6tSKFhgu_u7rGVCjX8wHdLmNY',
    appId: '1:626097842743:ios:82e8ba43dc686b705bedb2',
    messagingSenderId: '626097842743',
    projectId: 'smart-23dec',
    storageBucket: 'smart-23dec.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlutooth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEvnqspO6tSKFhgu_u7rGVCjX8wHdLmNY',
    appId: '1:626097842743:ios:82e8ba43dc686b705bedb2',
    messagingSenderId: '626097842743',
    projectId: 'smart-23dec',
    storageBucket: 'smart-23dec.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlutooth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkjCVL13E4dURPQAHtj3zqXiI8sz6ZE1E',
    appId: '1:626097842743:web:fcad1f04998f066a5bedb2',
    messagingSenderId: '626097842743',
    projectId: 'smart-23dec',
    authDomain: 'smart-23dec.firebaseapp.com',
    storageBucket: 'smart-23dec.firebasestorage.app',
    measurementId: 'G-TV9J1G5HPQ',
  );

}